### ISSUE TITLE
When building native modules, `npm rebuild` will try to access the Internet

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/nodejs-buildpack#53]
Steps to reproduce:

1.) Create an empty folder.
2.) Add this `package.json` file.

```
{
  "name": "bson-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bson-ext": "^0.1.13"
  },
  "engines": {
    "node": "4.3.2"
  }
}
```

3.) Add this `index.js` file.

```
var bson = require('bson-ext');
var http = require('http');

http.createServer(function (req, res) {
      res.writeHead(200, {'Content-Type': 'text/plain'});
      for (var env in process.env) {
          res.write(env + '=' + process.env[env] + '\n');
      }
      res.end();
}).listen(process.env.PORT || 3000);
```

4.) Run `npm install`.  That should build the library locally.  

```
# npm rebuild --unsafe-perm

> bson-ext@0.1.13 install /root/bson-test/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/bson-test/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory `/root/bson-test/node_modules/bson-ext/build'
```

You can confirm it's built by running `find . -name "*.node"`.  You should see this.

```
# find . -name "*.node"
./node_modules/bson-ext/build/Release/obj.target/bson.node
./node_modules/bson-ext/build/Release/bson.node
```

You can also run `npm start` and it should start without error.

5.) Push the application to a CF installation that does not have Internet access.  An easy way to simulate this is by unbinding all the staging security groups.

When pushed, staging will succeed but the module will not have been built and the application will fail to start.

The issue is that node-gyp will helpfully try to download the Node source code required to build the native module (node headers not module source code).  If you point node-gyp to the existing headers it will build without needing to go to the Internet.

https://github.com/nodejs/node-gyp/issues/235

The way to do that seems to be this.

```
npm rebuild --nodedir=$build_dir/.heroku/node 2>&1
```

Tested with a handful of native modules (bson-ext, libxmljs, brcypt and oracle) and they all work without needing the Internet.

**Comment by Dannyzen** [comment]
@dmikusa-pivotal Thanks for putting the issue in. We've completed this fix and it is now in the [develop](https://github.com/cloudfoundry/nodejs-buildpack/commits/develop) branch. We expect it to be included in master later this week.

**Comment by Dannyzen** [comment]
@dmikusa-pivotal This has been fixed and is now in master.

**Comment by warroyo** [comment]
I am using buildpack version 1.5.5 and still seeing this issue when trying to start the application. I am using the oracle native module.

here is my error:
````
 Rebuilding any native modules
       > oracledb@1.9.3 install /tmp/staged/app/node_modules/oracledb
       > node-gyp rebuild
       gyp ERR! configure error
       gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
       gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
       gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
       gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
       gyp ERR! System Linux 3.19.0-51-generic
       gyp ERR! command "/tmp/staged/app/.heroku/node/bin/node" "/tmp/staged/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/staged/app/node_modules/oracledb
       gyp ERR! node -v v4.2.5
       gyp ERR! node-gyp -v v3.0.3
       gyp ERR! not ok
       npm ERR! Linux 3.19.0-51-generic
       npm ERR! argv "/tmp/staged/app/.heroku/node/bin/node" "/tmp/staged/app/.heroku/node/bin/npm" "rebuild"
       npm ERR! node v4.2.5
       npm ERR! npm  v2.14.12
       npm ERR! code ELIFECYCLE
       npm ERR! oracledb@1.9.3 install: `node-gyp rebuild`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the oracledb@1.9.3 install script 'node-gyp rebuild'.
       npm ERR! This is most likely a problem with the oracledb package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node-gyp rebuild
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls oracledb
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/staged/app/npm-debug.log
-----> Build failed
````
